### ISSUE TITLE
Can we put time stamp in facility.json ?

### ISSUE THREAD

**Issue by ygonno** [ISDCF/registries-server#3]
It would be beneficial putting time stamp in [facility.json](http://registry.isdcf.com/facilities), so that we can find when the list was updated.

Can I consider http://registry.isdcf.com/facilities is the right URL to get the latest facility.json ?

**Comment by radford-for-smpte** [comment]
> It would be beneficial putting time stamp in [facility.json](http://registry.isdcf.com/facilities), so that we can find when the list was updated.

The last modified time of the JSON data is currently available as the `Last-Modified` HTTP Response header, but I tend to agree that the value should be duplicated in the JSON itself. @palemieux do you agree?

> Can I consider http://registry.isdcf.com/facilities is the right URL to get the latest facility.json ?

Yes indeed @ygonno that URL will always be the latest data.
